### ISSUE TITLE
Compile breaks on Debian 32bit ARM

### ISSUE THREAD

**Issue by Bazmundi** [rorchard/FuzzyCLIPS#4]
can't find ltermcap

**Comment by Bazmundi** [comment]
Fixed with:

sudo apt-get install libncurses5-dev

**Comment by pquentin** [comment]
I'm glad that you found the solution! Closing.

**Comment by Bazmundi** [comment]
Good job you saving fzclips.  I have it running on a C.H.I.P. now.
